blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yuis-ice/wasm-boilerplate/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/yuis-ice/wasm-boilerplate/wiki
    about: Check the wiki for detailed documentation and guides
  - name: 🆘 Support
    url: https://github.com/yuis-ice/wasm-boilerplate/discussions/categories/q-a
    about: Get help from the community in our Q&A discussions
  - name: 📧 Email Support
    url: mailto:jobs.fumiya@pm.me
    about: Contact the maintainer directly for private matters
